# ===============================
# SERVER CONFIG
# ===============================
server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://interchange.proxy.rlwy.net:16436/railway
spring.datasource.username=root
spring.datasource.password=zukwaxIXVshyPpSRPIxpRAsimVyHHnje

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret=ChronoSyncSuperSecretKeyForJWTAuthentication1234567890SecureKey
jwt.expiration=86400000
# ===============================
# DATABASE CONFIG
# ===============================
#spring.datasource.url=jdbc:mysql://localhost:3306/chronosync_db
#spring.datasource.username=chronosync
#spring.datasource.password=ChronoSync@123
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.open-in-view=false

# Remove explicit dialect (Hibernate auto-detects)
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# ===============================
# LOGGING (IMPORTANT FOR VERIFICATION)
# ===============================

# Show SQL clearly
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Show scheduler logs
#logging.level.org.springframework.scheduling=DEBUG

# Show application logs clearly
#logging.level.root=INFO

#jwt.secret=ChronoSyncSecretKey12345678901234567890
#jwt.expiration=86400000


# ===============================
# SCHEDULER TEST MODE (OPTIONAL)
# ===============================
# If your @Scheduled uses fixedRate, keep in code.
# If using cron, temporarily set it to every 1 minute:
# Example cron expression for every 1 minute:
# 0 * * * * *



